In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import os
import glob
import pandas as pd
import pickle

import json

import numpy as np

import re

In [3]:
DATA_PATH="data/"

In [4]:
glob.glob(DATA_PATH + "/*.pkl")

['data/extracted_questions_20250202_parcial_02.pkl',
 'data/extracted_questions_20250202_parcial_01.pkl',
 'data/extracted_questions_20250203_parcial_01.pkl',
 'data/extracted_questions_20250202_parcial_03.pkl',
 'data/llama_deduplicated_reference_titles_20250205_02.pkl',
 'data/chunks_normas_new.pkl',
 'data/extracted_questions_20241029.pkl',
 'data/extracted_questions_20250203_final.pkl']

In [5]:
with open(DATA_PATH + "llama_deduplicated_reference_titles_20250205_02.pkl", "rb") as input_file:
    llama_deduplicated_reference_titles = pickle.load(input_file)

In [6]:
llama_deduplicated_reference_titles

['AD PGFN nº 3 de 18 de setembro de 2008',
 'ADI RFB nº 12, de 2016',
 'Acordo sobre o Novo Banco de Desenvolvimento',
 'Anexo ao Decreto nº 361, de 10 de dezembro de 1991',
 'Ação Declaratória de Inconstitucionalidade – ADI nº 5.422',
 'Circular do Banco Central do Brasil nº 3.432, de 3 de fevereiro de 2009',
 'Constituição Federal de 1988',
 'Convenção de Viena, Decreto nº 56.435, de 8 de junho de 1965',
 'Convênio de Criação de um Conselho de Cooperação Aduaneira',
 'Decisão Cosit nº 2, de 2000',
 'Decreto nº 85.306, de 30 de outubro de 1980, capítulo II, art. 7, item 1, “e”, do Protocolo sobre Privilégios, Isenções e Imunidades da Intelsat',
 'PMF nº 227, de 1980',
 'PMF nº 454, de 1977',
 'Parecer SEI Nº 110/2018/CRJ/PGACET/PGFN-MF, aprovado pelo Despacho nº 348/2020/PGFN-ME, de 26 de agosto de 2020',
 'Parecer SEI nº 10167/2021/ME',
 'Parecer nº 93/2018/DECOR/CGU/AGU',
 'Portaria Conjunta SRF/TSE nº 74, de 10 de janeiro de 2006',
 'Resolução CGPC nº 26, de 29 de setembro de 2008'

In [8]:
import Levenshtein

In [9]:
with open(DATA_PATH + "normas_full.json", 'r') as file:
    normas_json = json.load(file)

In [10]:
all_extracted_docs_titles = np.sort(list(normas_json.keys()))

In [11]:
all_extracted_docs_titles[0]

'Ato Declaratório Cosar nº 47.txt'

In [13]:
all_extracted_docs_titles.shape

(332,)

In [73]:
# Convert Levenshtein distance into a square distance matrix
distances = np.array([[1.0 - Levenshtein.jaro_winkler(a, b, prefix_weight=0.1) for b in llama_deduplicated_reference_titles] for a in all_extracted_docs_titles])

In [74]:
distances.shape

(332, 400)

In [86]:
np.argsort(distances[2])[:100]

array([ 30,  28,  33,  29,  32,  31,  27,  25,  26,  34,  23,  53,  36,
        35,  57,  56,  42,  51,  52,  40,  49,  39,  54,  24,  21,  55,
        41,  47,  44,  48,  37,  45,  46,  38,  22,  43,  50,   4, 245,
       391, 124, 118, 255, 111, 131, 126, 106, 119, 107,  97, 116, 122,
       267, 101, 266, 109, 105, 129, 128,  98, 125,  92, 256, 127,  99,
       238, 115,  96,  90,  95, 104,  91, 259, 249,  93, 263, 395, 110,
       117,  16, 264, 242, 244, 396, 130, 260, 132, 248, 262, 246, 252,
        94, 227, 261, 133,   5, 251, 268, 265, 398])

In [87]:
np.argmin(distances[2])

30

In [88]:
distances[0][30]

0.17906144781144773

In [76]:
all_extracted_docs_titles[2]

'Ato Declaratório Interpretativo SRF nº 2.txt'

In [91]:
llama_deduplicated_reference_titles[29]

'Ato Declaratório Interpretativo SRF nº 2, de 27 de março de 2007'

In [57]:
np.array(llama_deduplicated_reference_titles)[[27, 25, 26]]

array(['Ato Declaratório Interpretativo RFB nº 3, de 27 de abril de 2016',
       'Ato Declaratório Interpretativo RFB nº 1, de 18 de janeiro de 2016',
       'Ato Declaratório Interpretativo RFB nº 18, de 6 de dezembro de 2007'],
      dtype='<U144')

In [90]:
np.array(llama_deduplicated_reference_titles)[np.argsort(distances[2])[:20]]

array(['Ato Declaratório Interpretativo SRF nº 24, de 4 de outubro de 2004',
       'Ato Declaratório Interpretativo SRF nº 14, de 4 de maio de 2004',
       'Ato Declaratório Interpretativo SRF nº 8, de 23 de abril de 2003',
       'Ato Declaratório Interpretativo SRF nº 2, de 27 de março de 2007',
       'Ato Declaratório Interpretativo SRF nº 7, de 25 de março de 2004',
       'Ato Declaratório Interpretativo SRF nº 26, de 26 de dezembro de 2003',
       'Ato Declaratório Interpretativo RFB nº 3, de 27 de abril de 2016',
       'Ato Declaratório Interpretativo RFB nº 1, de 18 de janeiro de 2016',
       'Ato Declaratório Interpretativo RFB nº 18, de 6 de dezembro de 2007',
       'Ato Declaratório Interpretativo nº 16, de 22 de dezembro de 2005',
       'Ato Declaratório Executivo RFB nº 2, de 6 de março de 2024',
       'Ato Declaratório SRF nº 3, de 7 de janeiro de 1999',
       'Ato Declaratório Normativo CST nº 11, de 1978',
       'Ato Declaratório Normativo CST nº 10, de 1991'

In [68]:
distances[2][np.argsort(distances[2])[:100]]

array([0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.30305207, 0.3040404 , 0.30606061, 0.3076281 , 0.30845552,
       0.30998217, 0.31043895, 0.31110763, 0.31277056, 0.31738136,
       0.31938131, 0.3222957 , 0.32260188, 0.32287157, 0.33049242,
       0.33305653, 0.33796864, 0.39335792, 0.41791542, 0.42027417,
       0.42377594, 0.42377594, 0.42438882, 0.42545797, 0.42709995,
       0.42709995, 0.42770563, 0.42887689, 0.43073593, 0.43073593,
       0.43320673, 0.43320673, 0.43527019, 0.43646785, 0.43719244,
       0.43719244, 0.43829859, 0.43961039, 0.43961039, 0.43961039,
       0.43961039, 0.43961039, 0.44199134, 0.44264069, 0.44264069,
       0.44405594, 0.44556467, 0.44556467, 0.44677813, 0.44677813,
       0.44677813, 0.44677813, 0.44781145, 0.44781145, 0.44838

In [78]:
import parasail

In [92]:
result = parasail.sw(all_extracted_docs_titles[2], llama_deduplicated_reference_titles[29], 2, 1, parasail.blosum62)

print("Score:", result.score)
print("End Query:", result.end_query)
print("End Ref:", result.end_ref)

Score: 157
End Query: 40
End Ref: 40


In [82]:
print("Score:", result.score)
print("End Query:", result.end_query)
print("End Ref:", result.end_ref)

Score: 157
End Query: 40
End Ref: 40


In [107]:
from Bio.Align import PairwiseAligner

# Initialize the aligner
aligner = PairwiseAligner()

# Set parameters for Smith-Waterman (local) alignment
aligner.mode = 'global'  # 'global' for Needleman-Wunsch, 'local' for Smith-Waterman
aligner.match_score = 2
aligner.mismatch_score = -1
aligner.open_gap_score = -2
aligner.extend_gap_score = -1.5

In [108]:
alignments = aligner.align(str(all_extracted_docs_titles[2].split(".")[0]), 
                           str(llama_deduplicated_reference_titles[29]))

# Print results
for alignment in alignments:
    print(alignment)
    print("Alignment score:", alignment.score)

Ato Declaratório Interpretativo SRF nº 2------------------------
||||||||||||||||||||||||||||||||||||||||------------------------
Ato Declaratório Interpretativo SRF nº 2, de 27 de março de 2007

Alignment score: 43.5


In [112]:
alignments = aligner.align(str(all_extracted_docs_titles[2].split(".")[0]), 
                           str(llama_deduplicated_reference_titles[30]))

# Print results
for alignment in alignments:
    print(alignment)
    print("Alignment score:", alignment.score)

Ato Declaratório Interpretativo SRF nº 2--------------------------
||||||||||||||||||||||||||||||||||||||||--------------------------
Ato Declaratório Interpretativo SRF nº 24, de 4 de outubro de 2004

Alignment score: 40.5


In [116]:
alignments = aligner.align(str(all_extracted_docs_titles[2].split(".")[0]), 
                           str(llama_deduplicated_reference_titles[34]))

for alignment in alignments:
    print(alignment)
    print("Alignment score:", alignment.score)

Ato Declaratório Interpretativo ---------------------SRF nº 2---
||||||||||||||||||||||||||||||||---------------------...|..||---
Ato Declaratório Interpretativo nº 16, de 22 de dezembro de 2005

Alignment score: 28.0
Ato Declaratório Interpretativo S---------------------RF nº 2---
||||||||||||||||||||||||||||||||.---------------------..|..||---
Ato Declaratório Interpretativo nº 16, de 22 de dezembro de 2005

Alignment score: 28.0
Ato Declaratório Interpretativo SR---------------------F nº 2---
||||||||||||||||||||||||||||||||..---------------------.|..||---
Ato Declaratório Interpretativo nº 16, de 22 de dezembro de 2005

Alignment score: 28.0
Ato Declaratório Interpretativo SRF--------------------- nº 2---
||||||||||||||||||||||||||||||||...---------------------|..||---
Ato Declaratório Interpretativo nº 16, de 22 de dezembro de 2005

Alignment score: 28.0
Ato Declaratório Interpretativo--- SRF nº 2---------------------
|||||||||||||||||||||||||||||||---|...|..||--------------------

In [117]:
alignments = aligner.align(str(llama_deduplicated_reference_titles[34]),
                           str(all_extracted_docs_titles[2].split(".")[0]))

for alignment in alignments:
    print(alignment)
    print("Alignment score:", alignment.score)

Ato Declaratório Interpretativo nº 16, de 22 de dezembro de 2005
||||||||||||||||||||||||||||||||---------------------...|..||---
Ato Declaratório Interpretativo ---------------------SRF nº 2---

Alignment score: 28.0
Ato Declaratório Interpretativo nº 16, de 22 de dezembro de 2005
||||||||||||||||||||||||||||||||.---------------------..|..||---
Ato Declaratório Interpretativo S---------------------RF nº 2---

Alignment score: 28.0
Ato Declaratório Interpretativo nº 16, de 22 de dezembro de 2005
||||||||||||||||||||||||||||||||..---------------------.|..||---
Ato Declaratório Interpretativo SR---------------------F nº 2---

Alignment score: 28.0
Ato Declaratório Interpretativo nº 16, de 22 de dezembro de 2005
||||||||||||||||||||||||||||||||...---------------------|..||---
Ato Declaratório Interpretativo SRF--------------------- nº 2---

Alignment score: 28.0
Ato Declaratório Interpretativo nº 16, de 22 de dezembro de 2005
|||||||||||||||||||||||||||||||---|...|..||--------------------

In [125]:
import collections

In [147]:
def get_tokens(s):
  if not s: return []
  return normalize_document_title(s)

In [227]:
def compute_f1(a_gold, a_pred):
    gold_toks = get_tokens(a_gold)
    pred_toks = get_tokens(a_pred)
    
    print(f"gold_toks={gold_toks}, pred_toks={pred_toks}")
    
    common = collections.Counter(gold_toks) & collections.Counter(pred_toks)
    num_same = sum(common.values())
    
    if len(gold_toks) == 0 or len(pred_toks) == 0:
        # If either is no-answer, then F1 is 1 if they agree, 0 otherwise
        return int(gold_toks == pred_toks)
    
    if num_same == 0:
        return 0
    
    precision = 1.0 * num_same / len(pred_toks)
    recall = 1.0 * num_same / len(gold_toks)
    f1 = (2 * precision * recall) / (precision + recall)
    
    return f1

In [188]:
compute_f1(all_extracted_docs_titles[2].split(".")[0], llama_deduplicated_reference_titles[34])

gold_toks=['ato', 'declaratório', 'interpretativo', 'srf', '2'], pred_toks=['ato', 'declaratório', 'interpretativo', '16', '22', 'dezembro', '2005']


0.5

In [189]:
compute_f1(all_extracted_docs_titles[2].split(".")[0], llama_deduplicated_reference_titles[33])

gold_toks=['ato', 'declaratório', 'interpretativo', 'srf', '2'], pred_toks=['ato', 'declaratório', 'interpretativo', 'srf', '8', '23', 'abril', '2003']


0.6153846153846154

In [190]:
compute_f1(all_extracted_docs_titles[2].split(".")[0], llama_deduplicated_reference_titles[32])

gold_toks=['ato', 'declaratório', 'interpretativo', 'srf', '2'], pred_toks=['ato', 'declaratório', 'interpretativo', 'srf', '7', '25', 'março', '2004']


0.6153846153846154

In [191]:
compute_f1(all_extracted_docs_titles[2].split(".")[0], llama_deduplicated_reference_titles[31])

gold_toks=['ato', 'declaratório', 'interpretativo', 'srf', '2'], pred_toks=['ato', 'declaratório', 'interpretativo', 'srf', '26', '26', 'dezembro', '2003']


0.6153846153846154

In [192]:
compute_f1(all_extracted_docs_titles[2].split(".")[0], llama_deduplicated_reference_titles[30])

gold_toks=['ato', 'declaratório', 'interpretativo', 'srf', '2'], pred_toks=['ato', 'declaratório', 'interpretativo', 'srf', '24', '4', 'outubro', '2004']


0.6153846153846154

In [193]:
compute_f1(all_extracted_docs_titles[2].split(".")[0], llama_deduplicated_reference_titles[29])

gold_toks=['ato', 'declaratório', 'interpretativo', 'srf', '2'], pred_toks=['ato', 'declaratório', 'interpretativo', 'srf', '2', '27', 'março', '2007']


0.7692307692307693

In [135]:
np.array(llama_deduplicated_reference_titles)[29:35]

array(['Ato Declaratório Interpretativo SRF nº 2, de 27 de março de 2007',
       'Ato Declaratório Interpretativo SRF nº 24, de 4 de outubro de 2004',
       'Ato Declaratório Interpretativo SRF nº 26, de 26 de dezembro de 2003',
       'Ato Declaratório Interpretativo SRF nº 7, de 25 de março de 2004',
       'Ato Declaratório Interpretativo SRF nº 8, de 23 de abril de 2003',
       'Ato Declaratório Interpretativo nº 16, de 22 de dezembro de 2005'],
      dtype='<U144')

In [153]:
DOCUMENT_TITLE_REGEX=r"(.+)\s+n?º\s*([0-9\.]+)[,\s]+de\s+([0-9]+)º?\s+de\s+(\w+)\s+de\s+([0-9]{4})|(.+)\s+n?º\s*([0-9\.]+)"

In [186]:
def normalize_document_title(which_title):
    m = re.match(DOCUMENT_TITLE_REGEX, which_title.lower())

    if m is None:
        normalized_title = which_title.lower().split()
    else:
        all_matches = np.array(list(m.groups()))

        normalized_title = []
        
        for which_match in all_matches:
            if which_match is not None:
                normalized_title += which_match.split()

    return normalized_title

In [187]:
normalize_document_title(all_extracted_docs_titles[2].split(".")[0])

['ato', 'declaratório', 'interpretativo', 'srf', '2']

In [235]:
f1_sim = np.array([[compute_f1(a.split(".txt")[0], b) for b in llama_deduplicated_reference_titles] for a in all_extracted_docs_titles])

gold_toks=['ato', 'declaratório', 'cosar', '47'], pred_toks=['ad', 'pgfn', '3', '18', 'setembro', '2008']
gold_toks=['ato', 'declaratório', 'cosar', '47'], pred_toks=['adi', 'rfb', '12']
gold_toks=['ato', 'declaratório', 'cosar', '47'], pred_toks=['acordo', 'sobre', 'o', 'novo', 'banco', 'de', 'desenvolvimento']
gold_toks=['ato', 'declaratório', 'cosar', '47'], pred_toks=['anexo', 'ao', 'decreto', '361', '10', 'dezembro', '1991']
gold_toks=['ato', 'declaratório', 'cosar', '47'], pred_toks=['ação', 'declaratória', 'de', 'inconstitucionalidade', '–', 'adi', '5.422']
gold_toks=['ato', 'declaratório', 'cosar', '47'], pred_toks=['circular', 'do', 'banco', 'central', 'do', 'brasil', '3.432', '3', 'fevereiro', '2009']
gold_toks=['ato', 'declaratório', 'cosar', '47'], pred_toks=['constituição', 'federal', 'de', '1988']
gold_toks=['ato', 'declaratório', 'cosar', '47'], pred_toks=['convenção', 'de', 'viena,', 'decreto', '56.435', '8', 'junho', '1965']
gold_toks=['ato', 'declaratório', 'cosar', '

IOPub data rate exceeded.
The Jupyter server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--ServerApp.iopub_data_rate_limit`.

Current values:
ServerApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
ServerApp.rate_limit_window=3.0 (secs)



In [236]:
np.argsort(f1_sim[0])[::-1][:10]

array([21, 35, 36, 40, 42, 52, 55, 57, 54, 34])

In [237]:
all_extracted_docs_titles[0]

'Ato Declaratório Cosar nº 47.txt'

In [238]:
llama_deduplicated_reference_titles[21]

'Ato Declaratório Cosar nº 47, de 27 de novembro de 2000'

In [239]:
np.argsort(f1_sim[1])[::-1][:10]

array([25, 27, 26, 34, 46, 45, 23, 29, 30, 31])

In [240]:
print(all_extracted_docs_titles[1])
print(llama_deduplicated_reference_titles[25])

Ato Declaratório Interpretativo RFB nº 1.txt
Ato Declaratório Interpretativo RFB nº 1, de 18 de janeiro de 2016


In [241]:
for i in range(f1_sim.shape[0]):
    j = np.argsort(f1_sim[i])[::-1][0]
    print(f"{i}\n{all_extracted_docs_titles[i]}\n{llama_deduplicated_reference_titles[j]}\n")

0
Ato Declaratório Cosar nº 47.txt
Ato Declaratório Cosar nº 47, de 27 de novembro de 2000

1
Ato Declaratório Interpretativo RFB nº 1.txt
Ato Declaratório Interpretativo RFB nº 1, de 18 de janeiro de 2016

2
Ato Declaratório Interpretativo SRF nº 2.txt
Ato Declaratório Interpretativo SRF nº 2, de 27 de março de 2007

3
Ato Declaratório Interpretativo SRF nº 24.txt
Ato Declaratório Interpretativo SRF nº 24, de 4 de outubro de 2004

4
Ato Declaratório Interpretativo SRF nº 5.txt
Ato Declaratório Interpretativo SRF nº 24, de 4 de outubro de 2004

5
Ato Declaratório PGFN nº 1.txt
Ato Declaratório PGFN nº 1, de 12 de março de 2018

6
Ato Declaratório PGFN nº 13.txt
Ato Declaratório PGFN nº 1, de 12 de março de 2018

7
Ato Declaratório PGFN nº 14.txt
Ato Declaratório PGFN nº 9, de 20 de dezembro de 2011

8
Ato Declaratório PGFN nº 2.txt
Ato Declaratório PGFN nº 9, de 20 de dezembro de 2011

9
Ato Declaratório PGFN nº 3.txt
Ato Declaratório PGFN nº 5, de 3 de maio de 2016

10
Ato Declaratóri

In [225]:
llama_deduplicated_reference_titles

['AD PGFN nº 3 de 18 de setembro de 2008',
 'ADI RFB nº 12, de 2016',
 'Acordo sobre o Novo Banco de Desenvolvimento',
 'Anexo ao Decreto nº 361, de 10 de dezembro de 1991',
 'Ação Declaratória de Inconstitucionalidade – ADI nº 5.422',
 'Circular do Banco Central do Brasil nº 3.432, de 3 de fevereiro de 2009',
 'Constituição Federal de 1988',
 'Convenção de Viena, Decreto nº 56.435, de 8 de junho de 1965',
 'Convênio de Criação de um Conselho de Cooperação Aduaneira',
 'Decisão Cosit nº 2, de 2000',
 'Decreto nº 85.306, de 30 de outubro de 1980, capítulo II, art. 7, item 1, “e”, do Protocolo sobre Privilégios, Isenções e Imunidades da Intelsat',
 'PMF nº 227, de 1980',
 'PMF nº 454, de 1977',
 'Parecer SEI Nº 110/2018/CRJ/PGACET/PGFN-MF, aprovado pelo Despacho nº 348/2020/PGFN-ME, de 26 de agosto de 2020',
 'Parecer SEI nº 10167/2021/ME',
 'Parecer nº 93/2018/DECOR/CGU/AGU',
 'Portaria Conjunta SRF/TSE nº 74, de 10 de janeiro de 2006',
 'Resolução CGPC nº 26, de 29 de setembro de 2008'

In [242]:
compute_f1("Ato Declaratório SRF nº 16.txt".split(".txt")[0], 'Ato Declaratório Interpretativo nº 16, de 22 de dezembro de 2005')

gold_toks=['ato', 'declaratório', 'srf', '16'], pred_toks=['ato', 'declaratório', 'interpretativo', '16', '22', 'dezembro', '2005']


0.5454545454545454

In [243]:
compute_f1("Ato Declaratório SRF nº 16.txt".split(".txt")[0], 'Ato Declaratório SRF nº 22, de 30 de abril de 1997')

gold_toks=['ato', 'declaratório', 'srf', '16'], pred_toks=['ato', 'declaratório', 'srf', '22', '30', 'abril', '1997']


0.5454545454545454

In [246]:
f1_sim[19][np.argsort(f1_sim[19])[::-1][:10]]

array([0.54545455, 0.54545455, 0.54545455, 0.54545455, 0.54545455,
       0.54545455, 0.54545455, 0.54545455, 0.54545455, 0.5       ])